root:
  children:
    - config
    - data
    - src

  config:
    children:
      - toml

  data:
    children:
      - cache
      - graph
      - orig

    cache:
      children:
        - fasta
        - features
        - inference
        - model

    graph:
      children:
        - html
        - png

    orig:
      children:
        - bam
        - fasta
        - gargammel
        - refseq

  src:
    children:
      - flow
      - inter
      - util
    inter:
      children:
        - cli
        - doc
        - repl
