root:
  children:
    - bin
    - config
    - data
    - src

  src:
    children:
      - inter
      - util
      - flow
    inter:
      children:
        - cli
        - doc
        - repl

  data:
    children:
      - orig
      - cache
      - graph
    orig:
      children:
        - bam
        - fasta
        - refseq
        - gargammel
    cache:
      children:
        - fasta
        - features
        - inference
        - model
    graph:
      children:
        - html
        - png
